Blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import (home, projects)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('', home, name='home'),
    path('projects', projects, name='projects'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('signin/', views.login, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

posts/urls.py
from django.urls import path
from .views import (
    post_list,
    user_post_list,
    post_create,
    post_detail,
    post_update,
    post_delete,
)

app_name = 'posts'

urlpatterns = [
    path('', post_list, name='post_list'),
    path('create', post_create, name='post_create'),
    path('user/<slug:author>', user_post_list, name='user_post_list'),
    path('<slug:post_slug>', post_detail, name='post_detail'),
    path('<slug:post_slug>/edit', post_update, name='post_update'),
    path('<slug:post_slug>/delete', post_delete, name='post_delete'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% block extracss %}
    {% endblock extracss %}
    <title> {% block title %} IchheisseFar {% endblock title %} </title>
</head>

<body>
    {% include 'parts/navbar.html' %}
    <div class="container-fluid">
        <div class="row mt-3">
            <div class="col-3">
                {% block left_sidebar %}
                {% endblock left_sidebar %}
            </div>
            <div class="col">
                {% block content %}
                {% endblock content %}
            </div>
            <div class="col-3">
                {% block right_sidebar %}
                {% endblock right_sidebar %}
            </div>
        </div>
    </div>

    <!-- Bootstrap JavaScript -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
    <script src="{% static 'bs-custom-file-input.min.js' %}"></script>

    <script src="https://kit.fontawesome.com/6afb3c4dc9.js" crossorigin="anonymous"></script>
</body>

</html>

templates/dashboard.html
{% extends "base.html" %}
{% block title %}
{{ user.username }}'s Dashboard
{% endblock title %}

{% block content %}



<div class="container">
    <div class="row">
        <div class="col col-6">
            <h3>My Profile</h3><br>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="card" style="width: 18rem;">
                        <img src="{{ form.initial.profile_pic.url }}" class="card-img-top" alt="profile picture">
                    </div>
                </div><br>
                <div class="custom-file mb-3">
                    <input type="file" class="custom-file-input" name="profile_pic" id="customFile" accept="image/*">
                    <label class="custom-file-label" for="customFile">Choose file</label>
                </div>
                <div class="form-row">
                    <div class="form-group col">
                        <label>First Name</label>
                        <input type="text" name="first_name" value="{{ form.first_name.value }}" class="form-control">
                    </div>
                    <div class="form-group col">
                        <label>Last Name</label>
                        <input type="text" name="last_name" value="{{ form.last_name.value }}" class="form-control">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col">
                        <label>Email</label>
                        <input type="email" name="email" value="{{ form.email.value }}" class="form-control" required>
                        <small class="form-text text-danger">
                            {{ form.email.errors.as_text }}
                        </small>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col">
                        <label>Username</label>
                        <input type="text" name="username" value="{{ form.username.value }}" class="form-control"
                            required>
                        <small class="text-danger">
                            {{ form.username.errors.as_text }}
                        </small>
                    </div>
                </div>
                <br>
                <!-- <div class="form-row">
                    <div class="form-group col">
                        <div class="custom-file mb-3">
                            <label class="custom-file-label" for="customFile">Choose a profile picture</label>
                            <input type="file" class="custom-file-input" name="image" id="customFile" accept="image/*">
                        </div>
                    </div>
                </div> -->
                {% if messages %}
                {% include "parts/alerts.html" %}
                {% endif %}
                <button class="btn btn-primary" type="submit">Save Changes</button>
            </form>
        </div>
    </div>
</div>




<!-- {{ form.as_p }} -->

{% endblock content %}

templates/home.html
{% extends "base.html" %}

{% block content %}

Home
{% endblock content %}

templates/login_form.html
{% extends "base.html" %}
{% block extracss %}
<style>
    .center {
        padding: 150px 0;
    }
</style>
{% endblock extracss %}
{% block title %}
Log In
{% endblock title %}

{% block content %}
<div class="center">
    <div class="col col-6 mx-auto">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <h3 class="text-center">Log In</h3><br>
            {% include "parts/alerts.html" %}
            <div class="form-row">
                <div class="form-group col">
                    <label>Email or Username</label>
                    <input type="text" name="id" class="form-control" required>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col">
                    <label>Password</label>
                    <input type="password" name="password" class="form-control" required>
                </div>
            </div>
            <br>
            <button class="btn btn-primary btn-block" type="submit">Log me in!</button>
        </form><br>
        <a href="{% url 'accounts:signup' %}">I need an account</a>
    </div>
</div>
{% endblock content %}

templates/post_create.html
{% extends 'base.html' %}

{% block title %}
Create
{% endblock title %}

{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'posts:post_list' %}">All Posts</a></li>
        <li class="breadcrumb-item active" aria-current="page">New Post</li>
    </ol>
</nav>
<div class="container">
    <div class="row">
        <div class="col col-6">
            <h3>New Post</h3><br>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label>Title</label>
                    <input type="text" name="title" class="form-control" required>
                </div>
                <div class="form-group">
                    <label>Content</label>
                    <textarea name="content" rows="10" class="form-control" required></textarea>
                </div>
                <div class="custom-file mb-3">
                    <input type="file" class="custom-file-input" name="image" id="customFile" accept="image/*">
                    <label class="custom-file-label" for="customFile">Choose file</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" name="draft" id="defaultCheck1">
                    <label class="form-check-label" for="defaultCheck1">
                        Draft
                    </label>
                </div><br>
                <label for="inlineFormCustomSelect">Publish Date</label>
                <div class="form-row" id="inlineFormCustomSelect">
                    <div class="col-md-3 mb-3">
                        <select class="custom-select mr-sm-2" name="publish_month" required id="id_publish_month">
                            {% for key, value in months.items %}
                            <option value="{{ key }}" {% if current.month == key %} selected {% endif %}>{{ value }}
                            </option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-md-3 mb-3">
                        <select class="custom-select mr-sm-2" name="publish_day" required id="id_publish_day">
                            {% for day in days %}
                            <option value="{{ day }}" {% if current.day == day %} selected {% endif %}>{{ day }}
                            </option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-md-3 mb-3">
                        <select class="custom-select mr-sm-2" name="publish_year" required id="id_publish_year">
                            {% for year in years %}
                            <option value="{{ year }}" {% if current.year == year %} selected {% endif %}>{{ year }}
                            </option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <button class="btn btn-primary" type="submit">Post!</button>
        </div>
        </form>
    </div>
</div>
{% endblock content %}

{% block right_sidebar %}
{% include "parts/side_dashboard.html" %}
{% endblock right_sidebar %}

templates/post_detail.html
{% extends 'base.html' %}

{% load static %}
{% load humanize %}
{% load urlify %}
{% load duration %}

{% block title %}
{{ post.title }}
{% endblock title %}

{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-light">
        <li class="breadcrumb-item"><a href="{% url 'posts:post_list' %}">All Posts</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ post.title }}</li>
    </ol>
</nav>
{% include "parts/alerts.html" %}
<div class="card mb-3">
    {% if post.image %}
    <img src="{{ post.image.url }}" class="card-img-top">
    {% endif %}

    <div class="card-body">
        <div class="row">
            <div class="col-9">
                <h4>{{ post.title }}</h4>
                <small>Author: <cite title="Source Title"><a class="text-secondary"
                            href="{% url 'posts:user_post_list' post.author.username %}">{{ post.author.username }}</a></cite><br>
                    {{ post.timestamp|naturaltime }}<br>
                    Read Time: {{ read_time|etr }}</small>
            </div>
            {% if user.is_authenticated %}
            <div class="col-3">
                <p>Share to:</p>
                <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">
                    <h3 class="fab fa-facebook mr-2"></h3>
                </a>
                <a href="https://twitter.com/home?status={{ instance.content|urlify }}%20{{ request.build_absolute_uri }}
                ">
                    <h3 class="fab fa-twitter mr-2"></h3>
                </a>
                <a
                    href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}&title={{ instance.title }}&summary={{ instance.content|urlify }}&source={{ request.build_absolute_uri }}">
                    <h3 class="fab fa-linkedin">
                    </h3>
                </a>
            </div>
            {% endif %}
        </div>
        <div class="row">
            <div class="container ml-2">
                <p>{{ post.content|linebreaks }}</p>
            </div>
        </div>
        {% if post.author == user or user.is_superuser %}
        <div class="row">
            <div class="container">
                <div class="btn-toolbar" role="toolbar">
                    <button type="button" class="btn btn-danger mr-2" data-toggle="modal" data-target="#deleteModal">
                        Delete
                    </button>
                    <form action="{% url 'posts:post_update' post.slug %}">
                        <button type="submit" class="btn btn-info">Update</button>
                    </form>
                </div>
            </div>
        </div>
        {% endif %}
    </div>

    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Delete {{ post.title }}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete this post?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <form action="{% url 'posts:post_delete' post.slug %}">
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block right_sidebar %}
{% include "parts/side_dashboard.html" %}
{% endblock right_sidebar %}

templates/post_list.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}
{% if 'user/' in request.path %}
All posts by {{ user_post }}
{% else %}
All posts
{% endif %}
{% endblock title %}

{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-light">
        {% if 'user/' in request.path %}
        <li class="breadcrumb-item"><a href="{% url 'posts:post_list' %}">All Posts</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ user_post }}'s posts</li>
        {% elif request.GET.q %}
        <li class="breadcrumb-item"><a href="{% url 'posts:post_list' %}">All Posts</a></li>
        {% if not posts %}
        <li class="breadcrumb-item active" aria-current="page">No results for "{{ request.GET.q }}"</li>
        {% else %}
        <li class="breadcrumb-item active" aria-current="page">Search results for "{{ request.GET.q }}"</li>
        {% endif %}
        {% else %}
        <li class="breadcrumb-item active" aria-current="page">All Posts</li>
        {% endif %}
    </ol>
</nav>
{% if messages %}
{% for message in messages %}
{% if not 'Username' in message.message and not 'login' in message.message %}
{% include "parts/alerts.html" %}
{% endif %}
{% endfor %}
{% endif %}

<div class="row justify-content-center mt-3">
    <div class="col align-self-center">
        {% for post in posts %}
        <div class="card mb-3">
            <div class="row no-gutters">
                {% if post.image %}
                <div class="col-md-4">
                    <img src="{{ post.image.url }}" class="card-img">
                </div>
                {% endif %}
                <div {% if post.image %} class="col-md-8" {% else %} class="col-md-12" {% endif %}>
                    <div class="card-body">
                        <h5 class="card-title">{{ post.title }} {% if post.is_updated %}
                            <span class="badge badge-pill badge-success">Updated</span>{% endif %}
                            {% if post.draft %}
                            <span class="badge badge-pill badge-danger">Draft</span>{% endif %}
                            {% if post.publish > current.date %}
                            <span class="badge badge-pill badge-info">Future</span>{% endif %}
                        </h5>
                        <footer class="blockquote-footer">via <cite title="Source Title"><a class="text-secondary"
                                    href="{% url 'posts:user_post_list' post.author.username %}">{{ post.author.username }}</a></cite>
                            {{ post.timestamp|naturaltime }}
                        </footer>
                        <br>
                        <p class="card-text">{{ post.content|truncatewords:21 }}</p>
                        <div style="text-align: end;">
                            <a href="{% url 'posts:post_detail' post.slug %}"
                                class="btn btn-primary text-right">view</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {% endfor %}
    </div>
</div>

<footer>
    <nav aria-label="Page navigation example sticky_top">
        <ul class="pagination justify-content-center">
            {% if posts.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ posts.previous_page_number }}&q={{ request.GET.q }}"
                    aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% endif %}

            {% for num in paginator.page_range %}
            {% if num != posts.number %}
            <li class="page-item"><a class="page-link" href="?page={{ num }}&q={{ request.GET.q }}">{{ num }}</a></li>
            {% else %}
            <li class="page-item active" aria-current="page">
                <span class="page-link">
                    {{ num }}
                    <span class="sr-only">(current)</span>
                </span>
                {% endif %}
                {% endfor %}

                {% if posts.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ posts.next_page_number }}&q={{ request.GET.q }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" aria-label="Previous">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            {% endif %}
        </ul>
    </nav>
</footer>
{% endblock content %}

{% block right_sidebar %}
{% include "parts/side_dashboard.html" %}
{% endblock right_sidebar %}

templates/post_update.html
{% extends 'base.html' %}

{% block title %}
{{ post.title }} | Update
{% endblock title %}

{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'posts:post_list' %}">All Posts</a></li>
        <li class="breadcrumb-item"><a href="{% url 'posts:post_detail' post.slug %}">{{ post.title }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">Update</li>
    </ol>
</nav>
<div class="container">
    <div class="row">
        <div class="col col-9">
            <h3>Update Post</h3><br>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label>Title</label>
                    <input type="text" name="title" value="{{ form.initial.title }}" class="form-control" required>
                </div>
                <div class="form-group">
                    <label>Content</label>
                    <textarea name="content" rows="10" class="form-control"
                        required>{{ form.initial.content }}</textarea>
                </div>
                <div class="custom-file mb-3">
                    <input type="file" name="image" id="customFile" accept="image/*" class="btn">
                    <label class="custom-file-label" for="customFile">Choose file</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" name="draft" id="defaultCheck1"
                        {% if form.initial.draft %} checked {% endif %}>
                    <label class="form-check-label" for="defaultCheck1">
                        Draft
                    </label>
                </div><br>
                <label for="inlineFormCustomSelect">Publish Date</label>
                <div class="form-row" id="inlineFormCustomSelect">
                    <div class="col-md-3 mb-3">
                        <select class="custom-select mr-sm-2" name="publish_month" required id="id_publish_month">
                            {% for key, value in months.items %}
                            <option value="{{ key }}" {% if form.initial.publish.month == key %} selected {% endif %}>
                                {{ value }}
                            </option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-md-3 mb-3">
                        <select class="custom-select mr-sm-2" name="publish_day" required id="id_publish_day">
                            {% for day in days %}
                            <option value="{{ day }}" {% if form.initial.publish.day == day %} selected {% endif %}>
                                {{ day }}
                            </option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-md-3 mb-3">
                        <select class="custom-select mr-sm-2" name="publish_year" required id="id_publish_year">
                            {% for year in years %}
                            <option value="{{ year }}" {% if form.initial.publish.year == year %} selected {% endif %}>
                                {{ year }}
                            </option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <button class="btn btn-primary" type="submit">Update</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block right_sidebar %}
{% include "parts/side_dashboard.html" %}
{% endblock right_sidebar %}

templates/projects.html
{% extends "base.html" %}

{% block title %}
Ichheissefar | Projects
{% endblock title %}

{% block content %}
<br>
<h1 class="text-center">
    Projects
</h1>
<br>
<div class="row align-items-center">
    <div class="col text-center">
        Coming Soon...
    </div>
</div>
{% include "parts/footer.html" %}
{% endblock content %}

templates/signup_form.html
{% extends 'base.html' %}
{% block title %}
Sign Up
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col col-6">
            <h3>Sign Up</h3><br>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col">
                        <label>First Name</label>
                        <input type="text" name="first_name" value="{{ ex_form.first_name }}" class="form-control">
                        {{ form.first_name.errors.as_text }}
                    </div>
                    <div class="form-group col">
                        <label>Last Name</label>
                        <input type="text" name="last_name" value="{{ ex_form.last_name }}" class="form-control">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col">
                        <label>Email</label>
                        <input type="email" name="email" value="{{ ex_form.email }}" class="form-control" required>
                        <small class="form-text text-danger">
                            {{ form.email.errors.as_text }}
                        </small>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col">
                        <label>Username</label>
                        <input type="text" name="username" value="{{ ex_form.username }}" class="form-control" required>
                        <small class="text-danger">
                            {{ form.username.errors.as_text }}
                        </small>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col">
                        <label>Password</label>
                        <input type="password" name="password1" class="form-control" required>
                    </div>
                    <div class="form-group col">
                        <label>Password Confirm</label>
                        <input type="password" name="password2" class="form-control" required>
                    </div>
                    <small class="text-danger">
                        {{ form.password2.errors.as_text }}
                    </small>
                </div>
                <br>
                <!-- <div class="form-row">
                    <div class="form-group col">
                        <div class="custom-file mb-3">
                            <label class="custom-file-label" for="customFile">Choose a profile picture</label>
                            <input type="file" class="custom-file-input" name="image" id="customFile" accept="image/*">
                        </div>
                    </div>
                </div> -->
                <button class="btn btn-primary" type="submit">Sign me up!</button>
            </form>
        </div>
    </div>
</div>


{{ form.initial.email }}
{% endblock content %}