Blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import (home, projects)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('', home, name='home'),
    path('projects', projects, name='projects'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('signin/', views.login, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

posts/urls.py
from django.urls import path
from .views import (
    post_list,
    user_post_list,
    post_create,
    post_detail,
    post_update,
    post_delete,
)

app_name = 'posts'

urlpatterns = [
    path('', post_list, name='post_list'),
    path('create', post_create, name='post_create'),
    path('user/<slug:author>', user_post_list, name='user_post_list'),
    path('<slug:post_slug>', post_detail, name='post_detail'),
    path('<slug:post_slug>/edit', post_update, name='post_update'),
    path('<slug:post_slug>/delete', post_delete, name='post_delete'),
]

posts/models.py
from django.db import models
from django.urls import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.utils import timezone
from Blog.settings import AUTH_USER_MODEL


def upload_location(instance, filename):
    return f"{instance.slug}/{filename}"


class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


class Post(models.Model):
    class Meta:
        ordering = ["-timestamp"]

    title = models.CharField(max_length=130)
    author = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location, null=True, blank=True)
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    is_updated = models.BooleanField(default=False)
    views = models.IntegerField(default=0)

    objects = PostManager()

    def __str__(self):
        return self.title

    # def get_absolute_url(self):
    #     return reverse("posts:post_detail", kwargs={"post_id": self.id})


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by('-id')
    if qs.exists():
        new_slug = f"{slug}-{qs.first().id}"
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_reciever(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(pre_save_post_reciever, sender=Post)

templates/parts/alerts.html
{% if messages %}
{% for message in messages %}
<div id="message">
    <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
        <strong>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            Ooops!
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            Yeaaah!
            {% else %}
            {{ message.tags|title }}
            {% endif %}
        </strong>
        {{ message }}
    </div>
</div>
{% endfor %}
{% endif %}

templates/parts/footer.html
<footer class="text-muted fixed-bottom">
    <div class="container text-center">

        <p><i class="fa fa-copyright"></i> Copyright {% now "Y" %} Farhood Hosseinzadeh</p>

    </div>
</footer>

templates/parts/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand ml-3" href="{% url 'home' %}">
        <img src="{% static 'Django_Logo.png' %}" height="30" class="d-inline-block align-top" alt="">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li {% if '/' == request.path %} class="nav-item active" {% else %} class="nav-item" {% endif %}>
                <a class="nav-link" href="{% url 'home' %}">Home</a>
            </li>
            <li {% if 'posts' in request.path %} class="nav-item active" {% else %} class="nav-item" {% endif %}>
                <a class="nav-link" href="{% url 'posts:post_list' %}">Blog</a>
            </li>
            <li {% if 'projects' in request.path %} class="nav-item active" {% else %} class="nav-item" {% endif %}>
                <a class="nav-link" href="{% url 'projects' %}">Projects</a>
            </li>
            <li class="nav-item dropdown ml-3">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Accounts
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% if user.is_authenticated %}
                    <a class="dropdown-item" href="{% url 'accounts:dashboard' %}">My Dashboard</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="javascript:{document.getElementById('logout').submit()}"
                        onclick="">Logout</a>
                    <form id="logout" method="POST" action="{% url 'accounts:logout' %}">
                        {% csrf_token %}
                        <input type="hidden">
                    </form>
                    {% else %}
		    <a class="dropdown-item" href="{% url 'accounts:signin' %}">Login</a>
                    <a class="dropdown-item" href="{% url 'accounts:signup' %}">Signup</a>
                    {% endif %}
                    <!-- <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a> -->
                </div>
            </li>
        </ul>
        {% if 'posts' in request.path %}
        <form action="{% url 'posts:post_list' %}" method="GET" class="form-inline my-2 my-lg-0">{% csrf_token %}
            <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search the Blog"
                value="{{ request.GET.q }}" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search <span
                    class="fas fa-search"></span></button>
        </form>
        {% endif %}
    </div>
</nav>

<!-- Login modal -->
<div class="modal fade" id="signupModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Login</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="formGroupExampleInput">Username</label>
                        <input type="text" name="username" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="formGroupExampleInput2">Password</label>
                        <input type="password" name="password" class="form-control">
                    </div>
                    <div class="row justify-content-end">
                        <div class="col">
                            <a href="{% url 'accounts:signup' %}">Need an account?</a>
                        </div>
                        <div class="col col-auto">
                            <button type="submit" class="btn btn-primary">Log me in</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

templates/parts/search_bar.html
<div class="container">
    <div class="row justify-content-center ml-1">
        <div class="align-self-center">
            <div>
                <form class="form-row">
                    <div class="form-group col">
                        <input class="form-control" type="search" placeholder="Search for anything" aria-label="Search">
                    </div>
                    <div class="form-group col-auto">
                        <button class="btn btn-outline-success" type="submit">Search <span
                                class="fas fa-search"></span></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

templates/parts/side_dashboard.html
<nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-light">
        {% if user.is_authenticated %}
        <li class="breadcrumb-item active" aria-current="page">
            {% if user.first_name %}
            {{ user.first_name }}'s Dashboard
            {% else %}
            {{ user.username }}'s Dashboard
            {% endif %}
            <a href="{% url 'accounts:dashboard' %}" class="ml-auto"><i class="fas fa-user-edit"></i></a>
        </li>
        {% else %}
        <li class="breadcrumb-item active" aria-current="page">
            Quick Login
        </li>
        {% endif %}
    </ol>
</nav>
{% if messages %}
{% for message in messages %}
{% if 'Username' in message.message or 'login' in message.message %}
{% include "parts/alerts.html" %}
{% endif %}
{% endfor %}
{% endif %}
<div class="sticky-top">
    {% if not user.is_authenticated %}
    <div class="card card-body">
        <form action="" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="formGroupExampleInput">Username</label>
                <input type="text" name="username" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="formGroupExampleInput2">Password</label>
                <input type="password" name="password" class="form-control" required>
            </div>
            <div class="row justify-content-end">
                <div class="col">
                    <a class="btn btn-outline-primary" href="{% url 'accounts:signup' %}">Need an account?</a>
                </div>
                <div class="col col-auto">
                    <button type="submit" class="btn btn-primary">Log me in</button>
                </div>
            </div>
        </form>
    </div>
    {% else %}
    <div class="card shadow rounded">
        {% if user.profile_pic %}
        <img src="{{ user.profile_pic.url }}" class="card-img-top" alt="profile-pic">
        {% endif %}
        <div class="card-body">
            <h5 class="card-title">
                {% if user.first_name %}
                {{ user.first_name }}
                {% else %}
                @{{ user.username }}
                {% endif %}
            </h5>
            {% if user.is_superuser or user.is_staff %}
            <p class="card-text">You have made
                {% if user.post_set.count == 0 %}
                no posts
                {% elif user.post_set.count == 1 %}
                <a href="{% url 'posts:user_post_list' user.username %}" class="text-decoration-none">1 post</a>
                {% else %}
                <a href="{% url 'posts:user_post_list' user.username %}" class="text-decoration-none">
                    {{ user.post_set.count }} posts</a>
                {% endif %}</p>
            {% endif %}
            <br>
            <div class="row">
                <form class="col" action="{% url 'accounts:logout' %}" method="POST">{% csrf_token %}
                    <button type="submit" class="btn btn-outline-primary">Logout</button>
                </form>
                {% if user.is_superuser or user.is_staff %}
                <div class="col col-auto">
                    <a href="{% url 'posts:post_create' %}" class="btn btn-primary"><span class="fas fa-plus"></span>
                        New
                        Post</a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
    {% endif %}
</div>